___________________________

# Using lazypredict to scan many models before digging in and exploring the best models

___________________________

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
import sklearn
import lazypredict

In [3]:
# importing the data into data frame
filename = r"../../data/raw/ACME-HappinessSurvey2020.csv"
df = pd.read_csv(filename)
df.describe()

,Y,X1,X2,X3,X4,X5,X6
count,126.000000,126.000000,126.000000,126.000000,126.000000,126.000000,126.000000
mean,0.547619,4.333333,2.531746,3.309524,3.746032,3.650794,4.253968
std,0.499714,0.800000,1.114892,1.023440,0.875776,1.147641,0.809311
min,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,0.000000,4.000000,2.000000,3.000000,3.000000,3.000000,4.000000
50%,1.000000,5.000000,3.000000,3.000000,4.000000,4.000000,4.000000
75%,1.000000,5.000000,3.000000,4.000000,4.000000,4.000000,5.000000
max,1.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000

In [4]:
from lazypredict.Supervised import LazyClassifier
from sklearn.model_selection import train_test_split

# format data
X = df.copy()
Y = X.Y
X = X.drop(["Y"], axis=1)

# Split into train and hold-out test
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [5]:
clf = LazyClassifier(verbose=0, ignore_warnings=True, custom_metric=None)
models, predictions = clf.fit(X_train, X_test, y_train, y_test)

In [ ]:
print(len(models))
models

26

,Accuracy,Balanced Accuracy,ROC AUC,F1 Score,Precision,Recall,Time Taken
Model,,,,,,,
ExtraTreeClassifier,0.653846,0.663636,0.636364,0.655385,0.674451,0.653846,0.022651
XGBClassifier,0.653846,0.663636,0.690909,0.655385,0.674451,0.653846,0.370523
RandomForestClassifier,0.615385,0.642424,0.715152,0.608516,0.672700,0.615385,0.151718
QuadraticDiscriminantAnalysis,0.615385,0.642424,0.648485,0.608516,0.672700,0.615385,0.104500
LabelPropagation,0.615385,0.642424,0.660606,0.608516,0.672700,0.615385,0.028159
BaggingClassifier,0.615385,0.630303,0.724242,0.615385,0.645221,0.615385,0.044705
ExtraTreesClassifier,0.615385,0.630303,0.696970,0.615385,0.645221,0.615385,0.126609
DecisionTreeClassifier,0.615385,0.630303,0.600000,0.615385,0.645221,0.615385,0.019931
LabelSpreading,0.576923,0.609091,0.648485,0.563603,0.644231,0.576923,0.021794
NearestCentroid,0.576923,0.584848,0.690909,0.578803,0.596154,0.576923,0.022953
NuSVC,0.538462,0.563636,0.612121,0.530220,0.583710,0.538462,0.023732
KNeighborsClassifier,0.500000,0.554545,0.593939,0.438596,0.625000,0.500000,0.036469
SVC,0.500000,0.554545,0.636364,0.438596,0.625000,0.500000,0.020929
AdaBoostClassifier,0.538462,0.551515,0.596970,0.538462,0.564569,0.538462,0.363895
BernoulliNB,0.538462,0.551515,0.684848,0.538462,0.564569,0.538462,0.033011
PassiveAggressiveClassifier,0.500000,0.530303,0.442424,0.484258,0.548611,0.500000,0.022574
DummyClassifier,0.423077,0.500000,0.500000,0.251559,0.178994,0.423077,0.019599
CalibratedClassifierCV,0.461538,0.496970,0.533333,0.435431,0.507808,0.461538,0.106620
LogisticRegression,0.461538,0.484848,0.533333,0.451923,0.494721,0.461538,0.025422
SGDClassifier,0.423077,0.475758,0.321212,0.352227,0.461538,0.423077,0.020077
GaussianNB,0.423077,0.451515,0.672727,0.404913,0.452991,0.423077,0.019290
LinearSVC,0.423077,0.451515,0.527273,0.404913,0.452991,0.423077,0.020986
LinearDiscriminantAnalysis,0.423077,0.451515,0.515152,0.404913,0.452991,0.423077,0.123079
RidgeClassifier,0.423077,0.451515,0.533333,0.404913,0.452991,0.423077,0.045641
RidgeClassifierCV,0.423077,0.451515,0.551515,0.404913,0.452991,0.423077,0.062547
Perceptron,0.346154,0.372727,0.363636,0.325568,0.357372,0.346154,0.020517

: